name: true_ledger_core
description: "Professional Business Software, Decentralized, Offline-First, Extendable and Adaptabable"
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.9.0
  pointycastle: ^3.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.12.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/ipfs_worker.html